#!/usr/bin/env python3
"""Report generator — synthesizes scan findings into structured reports."""

import sys, json, logging
from datetime import datetime
from typing import Dict, Any

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

SEVERITY_EMOJI = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFO": "⚪"}


def generate_markdown_report(scan_results: dict, dep_results: dict = None) -> str:
    lines = [
        "# 🛡️ NERV-VIPER Security Report",
        f"\n> Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "\n---\n",
        "## Executive Summary\n",
    ]

    stats = scan_results.get("stats", {})
    total = stats.get("total_findings", 0)
    by_sev = stats.get("by_severity", {})

    lines.append(f"- **Files Scanned:** {stats.get('files_scanned', 0)}")
    lines.append(f"- **Total Findings:** {total}")
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        count = by_sev.get(sev, 0)
        if count:
            lines.append(f"- {SEVERITY_EMOJI.get(sev, '')} **{sev}:** {count}")

    # Risk score
    weights = {"CRITICAL": 25, "HIGH": 10, "MEDIUM": 3, "LOW": 1}
    score = min(100, sum(by_sev.get(s, 0) * w for s, w in weights.items()))
    lines.append(f"\n### Risk Score: **{score}/100**\n")

    # Findings
    if scan_results.get("findings"):
        lines.append("## Detailed Findings\n")
        for i, f in enumerate(scan_results["findings"], 1):
            emoji = SEVERITY_EMOJI.get(f["severity"], "")
            lines.append(f"### {i}. {emoji} [{f['severity']}] {f['description']}")
            lines.append(f"- **ID:** `{f['id']}`")
            lines.append(f"- **File:** `{f['file']}` (line {f['line']})")
            lines.append(f"- **Match:** `{f['match']}`")
            lines.append("")
    else:
        lines.append("## ✅ No findings — clean scan\n")

    # Dependencies
    if dep_results and dep_results.get("manifests_found"):
        lines.append("## Dependency Analysis\n")
        lines.append(f"- **Manifests detected:** {dep_results['stats']['manifests_detected']}")
        lines.append(f"- **Ecosystems:** {', '.join(dep_results['stats']['ecosystems'])}")
        lines.append("")

    lines.append("---\n*Report generated by NERV-VIPER Execution Layer*")
    return "\n".join(lines)


def generate_report(scan_json_path: str, dep_json_path: str = None, output_path: str = None) -> Dict[str, Any]:
    with open(scan_json_path) as f:
        scan = json.load(f)
    dep = None
    if dep_json_path:
        with open(dep_json_path) as f:
            dep = json.load(f)

    md = generate_markdown_report(scan, dep)
    out = output_path or "security_report.md"
    with open(out, "w") as f:
        f.write(md)

    logger.info(f"Report written to {out}")
    return {"success": True, "output": out, "timestamp": datetime.utcnow().isoformat()}


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_report.py <scan_results.json> [dep_results.json] [output.md]")
        sys.exit(1)
    args = sys.argv[1:]
    result = generate_report(args[0], args[1] if len(args) > 1 else None, args[2] if len(args) > 2 else None)
    print(json.dumps(result, indent=2))
